# CONSTANT TO SETUP THE PROGRESS DB
TABLE_MIGRATION = 'migration_progress'
TABLE_MAP = 'migration_map'
TABLE_RECENT = 'migration_recent'
MIGRATION_DEMO = 1
MIGRATION_FULL = 2
STATUS_NEW = 1
STATUS_RUN = 2
STATUR_STOP = 3
STATUS_COMPLETE = 4
STATUS_KILL = 5
STATUS_CONFIGURING = 6
STATUS_PAYMENT = 7
DIR_UPLOAD = 'uploads'
DIR_PROCESS = 'processes'
CONFIG_FILE = '/etc/config.ini'
FLAG_STOP = 1
FLAG_KILL_ALL = 2

def 